### ISSUE TITLE
Is it possible to use Vim Plug to install this?

### ISSUE THREAD

**Issue by nikitavoloboev** [wakatime/vim-wakatime#43] opened 2016-10-03 21:05 UTC
I installed it with Vim Plug however I am not sure where I have to enter my API key.

Thank you for any help.

**Comment by alanhamlett** [comment] 2016-10-05 14:51
As long as the plugin is loading inside Vim, then it should prompt for the api key when first launching Vim. If it doesn't prompt, then it must already be entered in `~/.wakatime.cfg` located in your user home folder.

**Comment by bennyty** [comment] 2017-03-06 09:08
Can confirm that wakatime works fine with vim-plug. Plug is compatible with any plugin that is installable with Vundle.

**Comment by epeli** [comment] 2017-03-06 18:16
It does not prompt for me.  Using neovim.

**Comment by alanhamlett** [comment] 2017-03-07 03:41
Closing, since it's confirmed to work with Vim Plug.

**Closed by alanhamlett** 2017-03-07 03:41 UTC

**Comment by RanchoCooper** [comment] 2017-07-19 04:21
@alanhamlett  I install vim-wakatime successfully, and already prepare api-key in  ~/.wakatime.cfg

but, several days later, vim  did't recorded
